### ISSUE TITLE
Fan on command doesn't work

### ISSUE THREAD

**Issue by Automated-House** [KiraPC/ha-switchbot-remote#47]
Turning an IR fan on from HA doesn't work. The off command does.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:48:12 PM (1 occurrences)
Last logged: 9:48:12 PM

[545442487360] SwitchBotRemoteFan.async_turn_on() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 971, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1043, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 333, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SwitchBotRemoteFan.async_turn_on() takes 1 positional argument but 3 were given

**Comment by KiraPC** [comment]
@Automated-House Hello,

When this issue occurs? 

I guess this is related in the way the integration is called.

What HomeAssistant version do you have?

**Comment by Automated-House** [comment]
This occurs when turning the fan entity on
![image](https://github.com/KiraPC/ha-switchbot-remote/assets/17220004/88aeffb1-b744-4c3c-8fc8-3110ac353d46)

I'm on 2024.4.4

**Comment by KiraPC** [comment]
Fix released in 1.2.1
