### ISSUE TITLE
Started getting this, this morning...

### ISSUE THREAD

**Issue by itnassol** [KiraPC/ha-switchbot-remote#60]
Did a couple of minor updates this morning and noticed this...

![image](https://github.com/user-attachments/assets/a65d21c7-fc9f-4a01-bc32-be9c17de7163)

Thought is might have been the updates so rolled back to las night backup, and the errors were still there... tried reloading etc to no avail, run the debug and got this, hope it helps... 

2024-12-16 08:33:51.902 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry JR for switchbotremote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/__init__.py", line 36, in async_setup_entry
    remotes = await hass.async_add_executor_job(switchbot.remotes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switchbotremote/client/__init__.py", line 17, in remotes
    response = self.client.get("devices")
  File "/config/custom_components/switchbotremote/client/client.py", line 84, in get
    return self.request("GET", path, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/client/client.py", line 73, in request
    result = self.__request(method, path, **kwargs)
  File "/config/custom_components/switchbotremote/client/client.py", line 55, in __request
    raise HomeAssistantError(f"SwitchBot API server returns status {response.status_code}")
homeassistant.exceptions.HomeAssistantError: SwitchBot API server returns status 403
2024-12-16 08:33:51.937 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Jeff2 for switchbotremote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/__init__.py", line 36, in async_setup_entry
    remotes = await hass.async_add_executor_job(switchbot.remotes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switchbotremote/client/__init__.py", line 17, in remotes
    response = self.client.get("devices")
  File "/config/custom_components/switchbotremote/client/client.py", line 84, in get
    return self.request("GET", path, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/client/client.py", line 73, in request
    result = self.__request(method, path, **kwargs)
  File "/config/custom_components/switchbotremote/client/client.py", line 55, in __request
    raise HomeAssistantError(f"SwitchBot API server returns status {response.status_code}")
homeassistant.exceptions.HomeAssistantError: SwitchBot API server returns status 403

**Comment by telegrambeans** [comment]
Me too.
```
Logger: homeassistant.config_entries
Quelle: config_entries.py:640
Erstmals aufgetreten: 10:36:58 (5 Vorkommnisse)
Zuletzt protokolliert: 10:47:54

Error setting up entry Wohnzimmer Hub Mini IR for switchbotremote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/__init__.py", line 36, in async_setup_entry
    remotes = await hass.async_add_executor_job(switchbot.remotes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switchbotremote/client/__init__.py", line 17, in remotes
    response = self.client.get("devices")
  File "/config/custom_components/switchbotremote/client/client.py", line 84, in get
    return self.request("GET", path, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/switchbotremote/client/client.py", line 73, in request
    result = self.__request(method, path, **kwargs)
  File "/config/custom_components/switchbotremote/client/client.py", line 55, in __request
    raise HomeAssistantError(f"SwitchBot API server returns status {response.status_code}")
homeassistant.exceptions.HomeAssistantError: SwitchBot API server returns status 403
```

**Comment by KiraPC** [comment]
Hello guys,

I guess this is a API relation problem.

Please follow updates here: https://github.com/OpenWonderLabs/SwitchBotAPI/issues/374

**Comment by KiraPC** [comment]
Hello guys,

I've released a new pre-release version that workaround the problem in the meanwhile we have more info from switchbot.

Download the latest pre-release **1.3.2-rc.2** then go in the integration config page -> click on the 3 dots button -> reconfigure.

In the **host** input text put the string **https://api.switchbot.net** then save.

It now should works.

**Comment by itnassol** [comment]
Brilliant, nicely done.

**Comment by MikeBP13** [comment]
I get an error when I click reconfigure:
![Screenshot_20241216_214149_Home Assistant](https://github.com/user-attachments/assets/d801b9ac-34f8-4929-bc2d-82cf307f74b3)

**Comment by richsimpson** [comment]
Nice one. Quick work. Working for me again. 👍🏻

**Comment by seba1337** [comment]
I'm getting now this after the update. 
`  File "/config/custom_components/switchbotremote/__init__.py", line 35, in async_setup_entry
    switchbot = SwitchBot(token=entry.data["token"], secret=entry.data["secret"], host=entry.data["host"])
                                                                                       ~~~~~~~~~~^^^^^^^^
KeyError: 'host'`

**Comment by KiraPC** [comment]
> I'm getting now this after the update. `Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/switchbotremote/__init__.py", line 35, in async_setup_entry switchbot = SwitchBot(token=entry.data["token"], secret=entry.data["secret"], host=entry.data["host"]) ~~~~~~~~~~^^^^^^^^ KeyError: 'host'`

Could you please install the rc.3?

**Comment by seba1337** [comment]
Now at least starts without an error (compared to rc-2) and seems to work (but I didn't check if actions work - not at home). If I click configure I get some 500 error though and `    return OptionsFlowHandler(config_entry)
  File "/config/custom_components/switchbotremote/config_flow.py", line 205, in __init__
    host=self.data["host"] or switchbot_host
         ~~~~~~~~~^^^^^^^^
KeyError: 'host'`

It's rc-3.

**Comment by KiraPC** [comment]
Release 1.3.2
